#!/bin/bash

libtoolize --force --copy --automake
aclocal $ACLOCAL_FLAGS
autoheader
automake --gnu --copy --add-missing
autoconf
./configure --enable-maintainer-mode $@ || exit 1
if [ -z "$CVSCOMPILE_NO_MAKE" ]; then
  make
fi
