CPPFLAGS=-I/usr/local/include
LDFLAGS+=-L/usr/X11R6/lib -lX11  -lpopt 
LDFLAGS+=-L/usr/local/lib -lraw1394 -lcam1394
LDFLAGS+=-L/usr/local/lib -lopencv -lhighgui
CPPFLAGS+=-g

all: main-with-opencv

clean: 
	rm -f main-with-opencv *.o
