# $Id: Makefile.opencv,v 1.3 2003-03-13 11:27:10 yosimoto Exp $
# $Author: yosimoto $

#CXXFLAGS+=-I/usr/local/include
CXXFLAGS+=`opencv-config --cxxflags`
LDFLAGS+=-L/usr/X11R6/lib -lX11
LDFLAGS+=-L/usr/local/lib -lraw1394 -lcam1394
LDFLAGS+= `opencv-config --libs`
#CXXFLAGS+=-g

all: main-with-opencv

clean: 
	rm -f main-with-opencv *.o